### ISSUE TITLE
Incompatible with PHP 8.3

### ISSUE THREAD

**Issue by RobWoods-CPG** [samuelet/indexmenu#274]
When upgraded to PHP 8.3 it will no longer open the tree and let you see subfolder.s
The icon just spins for ever.

Errors:

```
2023-12-04 17:51:07
E_WARNING: Undefined array key "nons"
E:\CPG-Web\Wiki\lib\plugins\indexmenu\action.php(336)
#0 E:\CPG-Web\Wiki\lib\plugins\indexmenu\action.php(336): dokuwiki\ErrorHandler::errorHandler()
#1 E:\CPG-Web\Wiki\lib\plugins\indexmenu\action.php(170): action_plugin_indexmenu->print_index()
#2 E:\CPG-Web\Wiki\inc\Extension\EventHandler.php(80): action_plugin_indexmenu->_ajax_call()
#3 E:\CPG-Web\Wiki\inc\Extension\Event.php(74): dokuwiki\Extension\EventHandler->process_event()
#4 E:\CPG-Web\Wiki\inc\Ajax.php(27): dokuwiki\Extension\Event->advise_before()
#5 E:\CPG-Web\Wiki\lib\exe\ajax.php(22): dokuwiki\Ajax->__construct()
#6 {main}
2023-12-04 17:51:07
E_WARNING: Undefined array key "nopg"
...
2023-12-04 17:51:07
E_WARNING: Trying to access array offset on null
...
```

**Comment by Klap-in** [comment]
Could you update please to the latest version? I expect the warning is solved in that version. Can you confirm?

**Comment by Klap-in** [comment]
Please reopen if not yet fixed.
