### ISSUE TITLE
Current version incompatible with hogfather

### ISSUE THREAD

**Issue by MGChecker** [samuelet/indexmenu#291]
```
[Wed Jan 31 19:50:39.904746 2024] [php7:error] [pid 513293] [client 10.5.0.1:44344] PHP Fatal error:  Uncaught Error: Class 'dokuwiki\\File\\PageResolver' not found in /var/lib/dokuwiki/lib/plugins/indexmenu/syntax/indexmenu.php:773
Stack trace:
#0 /var/lib/dokuwiki/lib/plugins/indexmenu/syntax/indexmenu.php(459): syntax_plugin_indexmenu_indexmenu->parseNs()
#1 /usr/share/dokuwiki/inc/parser/renderer.php(117): syntax_plugin_indexmenu_indexmenu->render()
#2 /usr/share/dokuwiki/inc/parserutils.php(673): Doku_Renderer->plugin()
#3 /usr/share/dokuwiki/inc/parserutils.php(142): p_render()
#4 /usr/share/dokuwiki/inc/parserutils.php(89): p_cached_output()
#5 /usr/share/dokuwiki/inc/template.php(1580): p_wiki_xhtml()
#6 /var/lib/dokuwiki/lib/tpl/vector/conf/boxes.php(84): tpl_include_page()
#7 /var/lib/dokuwiki/lib/tpl/vector/main.php(123): include('/var/lib/dokuwi...')
#8 /usr/share/dokuwiki/inc/actions.php(27): include('/var/lib/dokuwi...')
#9 /usr/share/dokuwiki/doku.php(122): act_dispatch()
#10 {main}
thrown in /var/lib/dokuwiki/lib/plugins/indexmenu/syntax/indexmenu.php on line 773, referer: https://wiki.cde-ev.de/dokuwiki/doku.php?id=start&do=admin&page=extension&tab=search&q=
```

**Comment by Klap-in** [comment]
I try to support at least two releases of DokuWiki. 
I guess the v2023-09-17 release of Indexmenu still supports your DokuWiki version.

https://github.com/samuelet/indexmenu/releases

**Comment by MGChecker** [comment]
Is it possible to indicate compatibility of plugin versions with DokuWiki versions somehow, such that this can be made more clear?

**Comment by Klap-in** [comment]
Good point, I indicated it on the wiki page and as note in the first release where the compatibility changed.
